### ISSUE TITLE
Failed to load federation

### ISSUE THREAD

**Issue by laantungir** [MutinyWallet/mutiny-web#1277]
![Screenshot from 2024-08-07 14-48-02](https://github.com/user-attachments/assets/3d56314c-74cf-4829-90c9-6053a9eff248)

I'm getting this error from the web wallet.

I tried downloading and reimporting state.

I believe I have money in a lightning channel, other than what was in the federation. Is there a way to simply remove the federation and get to the lightning channel?

**Comment by bradstevens1** [comment]
Are you able to get it solved get ?

**Comment by benthecarman** [comment]
You may be open the app in safe mode and remove the federation

1. go to `https://app.mutinywallet.com?safe_mode=true`
2. restore from seed
3. remove the federation

**Comment by laantungir** [comment]
Unfortunately, there seems to be no change when using safe_mode.

Do you have an idea when the new update should be released?

**Comment by benthecarman** [comment]
Next few days

**Comment by Benzi0** [comment]
I came to say the same thing. I set up Mutiny wallet before the federations and still have sats in lightning channel not related to a federation. For a while I got the notice that a federation was shutting down and move my sats and figured I never had sats with that federation, so ignored it. Then I started to get the Failed to load federation error. Saving and loading the json file in a different browser doesn't do anything to change this, it just goes back to the same error. Hoping for a fix soon.

**Comment by laantungir** [comment]
Still no progress on this?

**Comment by TonyGiorgio** [comment]
Nothing yet, an update next week might allow you to rescan fedimint data.

**Comment by YawningGoat** [comment]
I’m also having this issue. Hope to see a fix soon!

**Comment by AnthonyRonning** [comment]
Which federation are you using? If they're no longer around then you can't connect to them.

**Comment by YawningGoat** [comment]
I can’t remember which federation it was, but I don’t think I have any sats there anyway. I only get an option to ‘reload’ with the error. I just want to disconnect from the federation and look at my lightning/on-chain sats.

**Comment by kenny47** [comment]
I have the same problem, can't remove the federation to at least access the rest of the funds. I tried to restore from seed as mentioned above, but without luck.

**Comment by Benzi0** [comment]
Are the developers just not going to provide any more support? This has been an issue for months and time is running short. There's another post on the same topic, but I don't see any fix to help us. Please, I would like to get my sats out of this wallet.

**Comment by YawningGoat** [comment]
Could disabling fedimint in safe mode fix this issue? It could allow people to force close lightning channels to be able to recover funds. I don’t have any remaining sats in the fedimint, but it’s currently restricting access to my on-chain and lightning wallets.

Related issues here: https://github.com/MutinyWallet/mutiny-web/issues/1295 https://github.com/MutinyWallet/mutiny-web/issues/1297

**Comment by benthecarman** [comment]
You can always edit your state file and remove the federation

**Comment by YawningGoat** [comment]
> You can always edit your state file and remove the federation

Thanks for getting in touch. I’ve now tried this and removed both the ‘fedimints/‘ and ‘federations’ parts of the json file, but still get the same error after importing the state from file. 

Is there anything else I can try?

If all else fails, would you recommend the [mutiny-data-recovery tool](https://github.com/MutinyWallet/mutiny-data-recovery?tab=readme-ov-file)?

**Comment by benthecarman** [comment]
Removing the whole item won't work, you need to make it an empty object.

**Comment by YawningGoat** [comment]
Thanks Ben, appreciate your help - all sorted now!

For others who are having this issue:

**Original json:**
```
"federations":{"federations":{"[data]":{"federation_code":"[data]"}},"version":1}
"fedimints/[data]":{"version":[data],"value":"[data]"}
```

**Amended json:**
```
"federations":{"federations":{},"version":1}
"fedimints/[data]":{"version":[data],"value":""}
```

**Comment by stackingsaunter** [comment]
Thanks, fixed my issue with it too

**Comment by laantungir** [comment]
Okay, so I emptied out the federations objects in the JSON file.

Now I get that I have another wallet open and running which is certainly not the case. Can I somehow force it to close other wallets that are running?


![Screenshot from 2024-12-15 08-35-11](https://github.com/user-attachments/assets/b937150e-d387-4d26-ad24-1b4db8ddebc4)

**Comment by Benzi0** [comment]
Same here, I edited the json and removed all this section:
"federations":{"federations":{"[data]":{"federation_code":"[data]"}},"version":1}
"fedimints/[data]":{"version":[data],"value":"[data]"}

I tried pasting:
"federations":{"federations":{},"version":1}
"fedimints/[data]":{"version":[data],"value":""}

But it didn't work and said there was an error, invalid json. 

I tried again but just removed entirely the section without anything else instead and it worked... up to the point that _laantungir_ got to, ie, that there is another wallet open and running. I haven't been able to go further. I don't have anything else open, and if I do somewhere where I can't access, how do I force close and open this new session instead?

**Comment by Benzi0** [comment]
Addendum to my earlier comment:
IT WORKED!
I downloaded a new browser (probably clearing the cache, etc in old would have worked too but I might have lost other things), and got it to open. The edited json file still seemed not to work, I'm not sure if trying to open that had any effect, but it seems just entering the seed phrase and rapidly clicking on the Admin tools and entering safe mode before it could get into the Reload Page loop seemed to work. Everything was on chain- perhaps because I used the [mutiny-data-recovery tool](https://github.com/MutinyWallet/mutiny-data-recovery?tab=readme-ov-file)? first? Then I sent the sats on their way.

**Comment by YawningGoat** [comment]
@laantungir I was getting that error, but did the following and it seemed to work (not sure which were the critical steps to stopping the error, but hope this works for you!):

1. Restored from seed in browser (I used incognito mode)
2. Save state as file
3. Close Mutiny browser tab and incognito window
4. Edit state as per my previous [comment](https://github.com/MutinyWallet/mutiny-web/issues/1277#issuecomment-2528632631)
5. Launched Mutiny again in a new incognito window
6. Clicked 'New Wallet' rather than 'Import Existing'
7. Once new wallet had loaded, go to settings -> emergency kit -> import state from file, and choose your amended json file.

@Benzi0 I've seen you recovereed funds, but for others that may have this issue: 
Don't paste the json directly from my comment. Anything that says [data], you need to keep what it says in the original json file.
