### ISSUE TITLE
Long close reason doesn't fit in modal

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-web#244]
![image](https://github.com/MutinyWallet/mutiny-web/assets/15256660/810e9de0-5747-410d-851f-35dc3d54a506)

**Comment by benalleng** [comment]
Saw an opportunity to fix this in #551 but I was wondering if you think just making it whitespace-normal looks ok orsome text alignment should be applied. I ask because for me personally I feel text-right looks odd curious what you think also @futurepaul 

whitespace-normal only:
![image](https://github.com/MutinyWallet/mutiny-web/assets/108441023/0255ec9e-3763-4a06-a2f9-0c27dbfab9ac)

**Comment by benthecarman** [comment]
yeah text-right looks best imo
