### ISSUE TITLE
Can´t recover wallet?

### ISSUE THREAD

**Issue by salvatoto** [MutinyWallet/mutiny-web#264]
I created a wallet last week with a balance. Successfully sent an LN transaction out as well. Wrote down my seed words.

This week I opened the app (added as PWA on mobile on Brave) and balance is 0. In Settings, ¨Tap to reveal seeds words¨, the seed words are different than those I backed up. 

I don´t see anywhere in the app to restore wallet, not even in ¨Secret Debug Tools¨

**Comment by TonyGiorgio** [comment]
We don't have the recover flow just yet. Though you can use the words to recover the on chain funds on another wallet. Did you happen to make a backup of the state file at all? That's where the lightning data is stored.

**Comment by salvatoto** [comment]
Ok. Wasn't much - was just testing wallet out. I'll just wait until the recover flow is in and then test that out.

**Comment by TonyGiorgio** [comment]
Really sorry about that. We're adding a warning about the recovery process on the next release.

Some questions about the Brave PWA on mobile: 
1. Is this on iOS or android? 
2. Do you happen to know if you've done any "clearing" or "wiping" of the browser manually since then? 
3. So the PWA app that's installed on your mobile home screen, that's what was cleared out? What happens if you just access `app.mutinywallet.com` from the normal browser? Still wiped out?
