### ISSUE TITLE
On-chain balance not showing new confirmed tx

### ISSUE THREAD

**Issue by extrapockets** [MutinyWallet/mutiny-web#382]
On-chain balance has not updated after my confirmed on-chain tx to Mutiny. Trying to add more funds to my Mutiny lightning balance. Tx has >10 confirmations, and I closed and relaunched Mutiny.

![Screenshot_20230720-100237](https://github.com/MutinyWallet/mutiny-web/assets/130774652/a5fe9d18-fb5b-4db1-8ae4-ceb5c7cbffa8)

**Comment by TonyGiorgio** [comment]
It's weird that it shows up in the transaction list but not in the balance, esp if it is confirmed. In the "admin tools" section of the settings, there's a "resync wallet" button. Maybe try that, restart, and then wait a few minutes to see if balance becomes accurate? 

Otherwise, some logs would help.

**Comment by extrapockets** [comment]
The resync solved my issue. Here's the logs from after the resync in case you're interested.

[mutiny-logs (7).txt](https://github.com/MutinyWallet/mutiny-web/files/12112011/mutiny-logs.7.txt)
