### ISSUE TITLE
Lost payments

### ISSUE THREAD

**Issue by CoderBoogs** [MutinyWallet/mutiny-web#446]
Over the last two days the wallet allowed two payments to process but funds are only showing up once. How do I locate the sats that were paid?

**Comment by benthecarman** [comment]
Can you be more clear on what happened? Sharing logs and screen shots helps as well

**Comment by CoderBoogs** [comment]
Sure.

So I created an invoice for 20k sats. I first paid it with cash app. cash app said the payment was pending so then I went to strike and paid the same invoice. Both apps said the payment confirmed but the 20k in sats from strike are missing. I contacted strike support and they said the payment was confirmed and they resolved the ticket. 

Ever since that day my wallet won't let me make any payments. Every single payment says no route. Even yo well known nodes like strike.

**Comment by CoderBoogs** [comment]
I got the logs but unsure how to post to this issue

**Comment by TonyGiorgio** [comment]
should be able to attach files by dragging and dropping a file into the comment box on github. Or email team@mutinywallet.com

**Comment by CoderBoogs** [comment]
Thanks and sent

**Comment by TonyGiorgio** [comment]
The logs don't go back far enough to show any incoming payments happen. However, here's the deal regarding duplicate payments from multiple senders. 

The wallet won't redeem multiple payments to the same invoice, no lightning wallet will. Odds are, either only strike or only cashapp made that successful payment. You will need proof that they made the payment, and that's with the preimage. If you click on the activity item for that payment in Mutiny, it will show you a preimage and a payment hash. Give that payment hash to strike and cash app and ask them if they have the preimage that hashes to it. Do NOT share the preimage with them.

If either of them do not have proof of payment, then they owe you the money back. If both of them give you the proof of payment, the money might have been taken from another node on the network, because it is not safe to share invoices to multiple payers. We can take a look to see if this happened due to a bug at the LSP level, but would be great to have proof from cashapp and strike with the preimage.

**Comment by CoderBoogs** [comment]
Thanks. I will do that now. What about not being able to make payments from the wallet anymore? Every invoice I try to pay says no route found

**Comment by TonyGiorgio** [comment]
I'll be taking a look at your logs more this week along with several others. Some people seem to be getting into a situation where payments to common destinations aren't fulfilling but there shouldn't be a problem. Did it work before but suddenly stop?

**Comment by CoderBoogs** [comment]
Yeah the wallet worked great. Problems started for me once I tried to pay the same invoice with cash app and strike. Cash app Lightning payments been very unreliable as of late so instead of waiting 12 hours to get notice my payment failed I tried to pay it with strike. Now I can't send a payment anywhere it's like they are locked up in the wallet. Still working with cash app and strike to see if I can track down that lost payment

**Comment by TonyGiorgio** [comment]
I've noticed payments being worse over the last few weeks, working on it more this week.

If you click on the payment in cash app or strike, does it show the preimage? I'm surprised strike doesn't show it, I thought they did.

**Comment by CoderBoogs** [comment]
Nah the cash app completed payment just shows the invoice paid

**Comment by CoderBoogs** [comment]
Okay thanks!

**Comment by Stargazerr1** [comment]
> Over the last two days the wallet allowed two payments to process but funds are only showing up once. How do I locate the sats that were paid?

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by CoderBoogs** [comment]
I think the sats came back. The activity log shows 2 Swept force actions with sats coming back into my wallet. Now they are on chain
