### ISSUE TITLE
Channel closed, on-chain empty

### ISSUE THREAD

**Issue by lundog** [MutinyWallet/mutiny-web#526]
Hi, same as others have experienced, I received 50k sats to open a channel, paid 10k fee, 15 minutes later the channel closed. Now the remaining 40k sats seem to be in limbo.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12567790/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Hey sorry about this, your funds should show up in a couple of days at most. Let us know if they don't.

```
2023-09-10 07:27:18.017 ERROR [lightning::ln::channelmanager:8344] A ChannelManager is stale compared to the current ChannelMonitor!
2023-09-10 07:27:18.017 ERROR [lightning::ln::channelmanager:8345]  The channel will be force-closed and the latest commitment transaction from the ChannelMonitor broadcast.
```

Looks like this is the stale channel manager bug. We're still tracking down the exact reason this happens but we suspect this happens when you close the app/page too quickly after an invoice has been paid. Waiting a couple seconds after a payment to close the app should help prevent this in the future.

**Comment by benthecarman** [comment]
For reference:

closing txid: d4392807df939e794535ad43ea4d5a4680aa588d28bb0321b5bd17fe009cd394

node id: 02158c97406ca9b97f43fee03cda088ae7873d3247ec5b920a050136803e4af7a6

**Comment by lundog** [comment]
Yep it worked. Thank you!
