### ISSUE TITLE
My channel capacity is less than expected

### ISSUE THREAD

**Issue by SergeyShirin** [MutinyWallet/mutiny-web#863]
I opened a channel with an onchain transaction from my onchain Mutiny balance. The transaction UTXO amount was 3 999 334 sats. After some LN transfers, I see that in my channel there are:
3 900 122 sats of outbound liquidity,
59 217 sats of reserve, and
1 sat of inbound liquidity.
The total channel capacity is 3 959 340 sats.
The difference between the amount of the UTXO of the transaction which opened the channel, and the current channel capacity is 39 994 sats. Where are these sats? I expected to have a channel which capacity would equal to the UTXO of the opening transaction: exactly 3 999 334 sats, not 3 959 340.)

It looks like a 1% fee, but at the moment of opening the channel (Oct-29, 2023) the declared fee was 10 000 sats. Moreover, the fee should be applicable to the money received via LN to the newly opened channel, while my money got there from my onchain Mutiny balance.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14141295/mutiny-logs.txt)
![Screenshot_20240201-113210](https://github.com/MutinyWallet/mutiny-web/assets/57345478/c32282c5-456b-4af6-b666-c2b4f1ccf313)

**Comment by benthecarman** [comment]
Like we explained in matrix, this screen isn't meant to give you an exact accounting for where every single sat is. The outbound liquidity is meant to represent a best estimate of what you can send out, the amount in your balance that is likely to be occupied in reserves when sending, and the inbound is what your counterparty has. A lot of these are estimates as they can change based on various factors (number of inflight htlcs, different on-chain fee rates, etc). If you close the channel you should get about what is your balance on the home screen, this screen is supposed to help you estimate how much you can send/receive in a payment, not a reflection of every small detail in the channel, because that would only confuse users further.

Since you opened the channel yourself there was no fee besides the on-chain fee you paid. The "missing" ~40k sats is merely just because this screen isn't trying to accurately display where every single sat is because what is more actionable is the max payment size.

**Comment by SergeyShirin** [comment]
Today I closed my channel, and I received onchain only that amount which previously was shown as my outbound liquidity. These 39994 sats were taken by Voltage. How can I receive my sats back?
