### ISSUE TITLE
Sent sats to myself, never appeared on Mutiny

### ISSUE THREAD

**Issue by MoreCredible** [MutinyWallet/mutiny-web#987]
Paid a lightning invoice to myself from Aqua Wallet to Mutiny. Did it all on my phone so I missed on mutiny where it says “Keep Mutiny open to complete transaction”.  Transaction cleared on Aqua, but the sats never came to my wallet on Mutiny. Block explorer says everything is done.

trans ID: 1b1f4a12faff06666a7c01bd73cc0a376647b98a3fb784dfdc15c223660fe145

Nostr pub key: npub1jwqcdljz6qcsdjrasjc54xcyy2xj0dxqc84f6r29sjva4dcqwntqwhqhwg

#support

**Comment by benthecarman** [comment]
Can you post your logs? It's in the emergency kit

**Comment by MoreCredible** [comment]
I would but it says that what I would be posting is too long. Is there another way to send it or post it?

**Comment by MoreCredible** [comment]
This better?
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14846210/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Perfect, will take a look

**Comment by TonyGiorgio** [comment]
LSP needed to restart. Could you restart mutiny and wait 10 - 30 seconds to see if it comes through?

**Comment by MoreCredible** [comment]
Killed the app, restarted. Waited.

still 0

**Comment by Duarte1971** [comment]
I'm in a similar situation, I used the Phoenix wallet, and the payment is pending. At Mutiny I have already restarted and I still don't receive the sats. 
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14853834/mutiny-logs.txt)

**Comment by MoreCredible** [comment]
My Buddy told me try writing down my seed phrase and see if that did the trick. Unfortunately still 0 sats. He sent me a small amount too just to test it.

**Comment by BTCSRB** [comment]
Hello, I have very similar problem so I didnt want to open new new issue. Like "Duarte1971", I've sent around 200k sats from Phoenix in order to open a channel. But the payment on Phoenix is still pending after 24 hours and on Mutiny nothing happened.

Note that I did the same by sending from Boltz (after swapping from Liquid) and the same happened but Boltz refunded my sats later. 

Here are Mutiny logs but there I do not see problematic transaction and its invoice, invoice in question is:

lnbc1330u1pnqcl4qpp5cuq39m57ndj89kns59wqwhz3n7zemkfsk965fycqpl60e3nh20xssp5jydx39t24a3kqgnq8mjmqd9k52dhyj2prn5007xctv64zl0wf2gqdqqcqzynxqyz5vq9qy9scqfppqvkghr9dyc8damja6z44ppvz38w52gpamrzjq0dpcf72w7rj43dnu4527vr88eve53a9u3yhlpw8khdyypygq7e76rx8g5qqgvgqqyqqqqlgqqqqx6cq2qgynmvp3knrlk5m3490fkd58052h0984ea92a6erhnr7ggp52sddng0ruk9j98xlu7dcylmycjejr4cz5dnfwmtutwqdk5taxjq2mxrgqukx7jp

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14858208/mutiny-logs.txt)

**Comment by BTCSRB** [comment]
Update: funds succesfully returned to Phoenix.

**Comment by TonyGiorgio** [comment]
For both of the logs above it's due to this: 

```
got an error reading event: Peer Sent Invalid Data
```

Unfortunately that's an error on the lightning service provider side that we've been experiencing off and on for the last few days with the launch. Higher load has been causing problems for the lightning node but we're working with Voltage to activatly troubleshoot it. The funds should return on the other side since the transactions never confirmed, sometimes it may take a day or two, but you'll need to work with them.

**Comment by Duarte1971** [comment]
I have already received the funds from Phoenix, thank you very much for the support and I wish that the recurring problematic situations can be resolved. Peace

**Comment by benthecarman** [comment]
Our LSP issues should be resolved now
